### ISSUE TITLE
What TCK tests do we need

### ISSUE THREAD

**Issue by Steve-Fontes** [eclipse/microprofile-opentracing#24] opened 2017-11-29 22:36 UTC
We have two major categories - tests for the automatic functions, and test for the explicit API functions.
Within each of those we have inbound requests and outbound requests
Within each of those we have synchronous and asynchronous flavors (If I screw up on some of the async concepts, please correct me, I have not worked with async a lot)

Within all of those we would need to test with multiple concurrent requests so that we don't get the thread state mixed up.

Maybe not all would be required for microprofile-opentracing 1.0, but I think we would want them eventually

1) Test synchronous automatic function - single requests
	a) Successful request 
		- Creates a single Span with information that matches spec
	b) Successful request makes a successful outbound request
		- Creates two Spans with information that matches spec, outound request Span is child of inbound request Span
	c) Failed request
	    - Creates Span with error information
	d) Successful request makes failed outbound request
		- Creates two Spans with information that matches spec, outound request Span is child of inbound request Span, outound request Span has error information
	e) ...
	
2) Test asynchronous automatic function - single requests
	a) Inbound request delivers response asynchronously from initial thread
	b) Outbound request get response asynchronously from initial thread
	c) Inbound request uses a thread pool to create outbound requests
	d) ...

3) Test synchronous explicit use of @Traced annotation
    a) Similar to automatic tests
	b) Apply @Traced to an internal business logic method (not an endpoint)
	c) Ensure @Trace(false) is honored
	d) ...

4) Test asynchronous explicit use of @Traced annotation
        a) Similar to automatic tests
	b) Apply @Traced to an internal business logic method (not an endpoint) that is invoked on a different thread from request thread
        c) ...
	
5) Test ability to use @Inject Tracer to access full io.opentracing API 
    a) ... 

6) Test multiple concurrent requests for each of the above types of tests.

**Comment by pavolloffay** [comment] 2017-11-30 10:49
4. b) might be complicated because I am not sure if we can propagate parent span there.

I think we should conceptually split it into 4 sections - server tracing, client tracing, `@Traced` and injectable tracer:

1. server side jax-rs tracing
* span with standard tags is created
* test that tracing extracts a context from inbound request
* span in handler is available via `tracer`
* error tags are added (needs clarification in the spec)
* test async handler

2. client jax-rs tracing
* request with standard tags
* test that context is injected into outbound request
* test that client span is a parent of the currently active span (here we have to create multiple requests in different threads with different parents, something like this https://github.com/pavolloffay/java-jaxrs/blob/e964e46e3fea3322afc39022e69f28187ae24b3a/opentracing-jaxrs2-itest/common/src/main/java/io/opentracing/contrib/jaxrs2/itest/common/AbstractClientTest.java#L241). 

3. `@Traced`
* change operation name for endpoint
* change operation name for handler class
* change operation one for handler class and override on endpoint
* disable handler method
* disable handler class
* disable class and enable method

4. tracer is injectable

**Comment by pavolloffay** [comment] 2017-12-05 16:40
regarding 2.2:

The goal is to test that client which is shared between multiple threads correctly identifies parent. The problem is that client implementations use thread pools so sometimes parent span is not correctly identified even though that it was correctly set in the thread which executes the client.

We need this test for both sync and async client api. See attached link in the previous comment.

cc @kgibm

**Comment by kgibm** [comment] 2017-12-07 01:25
@pavolloffay Please let me know if you have any thoughts on this plan for multi-threading:

1. Change `org.eclipse.microprofile.opentracing.tck.tracer.TestTracer.spanTree()` to `spanTrees` and return a `List<TestSpanTree>`, with each `TestSpanTree` representing one TCK request (i.e. a span with no parent).
2. Based on the `AbstractClientTest` code, send `N` requests concurrently, setting a unique identifier as a tag in each request and as a query parameter. Propagate the unique identifier down any outbound requests made by that request.
3. Process the result of `spanTrees`, checking that the unique identifier tag and query parameter match, and then recursively checking the child spans for the same unique identifier (using a lambda with the new `org.eclipse.microprofile.opentracing.tck.tracer.TestSpanTree.visitSpans(Consumer<? super TestSpan>)`).

**Comment by kgibm** [comment] 2017-12-08 01:02
After looking at the code, the `TestSpanTree` returned by `spanTree` already has a list of root spans (those without a parent), so item 1 is moot.

**Comment by kgibm** [comment] 2017-12-09 00:08
@Steve-Fontes @pavolloffay

Here's where I think we are (after PR #37):

>     Test synchronous automatic function - single requests
>     a) Successful request
>     - Creates a single Span with information that matches spec

Done in `OpentracingClientTests.testStandardTags`.

>     b) Successful request makes a successful outbound request
>     - Creates two Spans with information that matches spec, outound request Span is child of inbound request Span

Done in `OpentracingClientTests.testNestedSpans`.

>     c) Failed request
>     - Creates Span with error information

Partially done in `OpentracingClientTests.testError`. The part remaining is to catch an unhandled exception and add an `event=error` log entry with `error.object`. The code is already there to return, compare, and assert expected log entries.

>     d) Successful request makes failed outbound request
>     - Creates two Spans with information that matches spec, outound request Span is child of inbound request Span, outound request Span has error information

Not done yet but should be easy to add to `TestServerWebServices.nest`.

>     Test asynchronous automatic function - single requests
>     a) Inbound request delivers response asynchronously from initial thread

Done in `OpentracingClientTests.testAsyncLocalSpan`.

>     b) Outbound request get response asynchronously from initial thread

Not done yet.

>     c) Inbound request uses a thread pool to create outbound requests

Not done yet.

>     Test synchronous explicit use of @Traced annotation
>     a) Similar to automatic tests
>     b) Apply @Traced to an internal business logic method (not an endpoint)
>     c) Ensure @trace(false) is honored
> 
>     Test asynchronous explicit use of @Traced annotation
>     a) Similar to automatic tests
>     b) Apply @Traced to an internal business logic method (not an endpoint) that is invoked on a different thread from request thread

Not done yet.

>     Test ability to use @Inject Tracer to access full io.opentracing API

Done in `OpentracingClientTests.testLocalSpanHasParent`.

>     Test multiple concurrent requests for each of the above types of tests.

Partially done in `OpentracingClientTests.testMultithreadedNestedSpans`.

>     server side jax-rs tracing
> 
>     span with standard tags is created
>     test that tracing extracts a context from inbound request
>     span in handler is available via tracer

Done in `OpentracingClientTests.testStandardTags`.

>     error tags are added (needs clarification in the spec)

Partially done in `OpentracingClientTests.testError` (see above for details).

>     test async handler

Done in `OpentracingClientTests.testAsyncLocalSpan`.

>     client jax-rs tracing
> 
>     request with standard tags
>     test that context is injected into outbound request

Done in `OpentracingClientTests.testNestedSpans`.

>     test that client span is a parent of the currently active span (here we have to create multiple requests in different threads with different parents, something like this https://github.com/pavolloffay/java-jaxrs/blob/e964e46e3fea3322afc39022e69f28187ae24b3a/opentracing-jaxrs2-itest/common/src/main/java/io/opentracing/contrib/jaxrs2/itest/common/AbstractClientTest.java#L241).

Done from the Arquillian point of view, but not done yet for the nested client.

>     @Traced
> 
>     change operation name for endpoint
>     change operation name for handler class
>     change operation one for handler class and override on endpoint
>     disable handler method
>     disable handler class
>     disable class and enable method

Not done yet.

>     tracer is injectable

Done in `OpentracingClientTests.testLocalSpanHasParent`.

**Comment by kgibm** [comment] 2017-12-09 00:15
@pavolloffay 

> The goal is to test that client which is shared between multiple threads correctly identifies parent. The problem is that client implementations use thread pools so sometimes parent span is not correctly identified even though that it was correctly set in the thread which executes the client.

Can we just use [AsyncInvoker](https://docs.oracle.com/javaee/7/api/javax/ws/rs/client/Invocation.Builder.html#async--)? This will use a thread pool under the covers and the container can handle span propagation.

**Comment by kgibm** [comment] 2017-12-09 00:47
> >     d) Successful request makes failed outbound request
> >     - Creates two Spans with information that matches spec, outound request Span is child of inbound request Span, outound request Span has error information
> 
> Not done yet but should be easy to add to TestServerWebServices.nest.

Added in PR #37 in `OpentracingClientTests.testNestedSpansWithClientFailure`.

**Comment by pavolloffay** [comment] 2018-05-25 12:58
Already done I will close it

**Closed by pavolloffay** 2018-05-25 12:58 UTC
